[tool.poetry]
name = "swearbot"
version = "0.1.0"
description = "A discord bot that punishes cussing"
authors = ["James Wild <wild.james343@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = "^2.5.2"
anyio = "^4.9.0"
dotenv = "^0.9.9"
pynacl = "^1.5.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
