name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          export PYTHONUNBUFFERED=1
          pip install poetry

      - name: Set up Dependencies
        run: make install

      - name: Test
        run: make test

      - name: Coveralls
        uses: coverallsapp/github-action@v2
